package com.example.EmployeeLeaveManagement.dto;

import com.example.EmployeeLeaveManagement.enums.LeaveStatus;
import com.example.EmployeeLeaveManagement.enums.LeaveTypeEnum;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import java.time.LocalDate;

/**
 * Data Transfer Object (DTO) representing a leave request.
 * <p>This DTO is used for both submitting leave requests and returning
 * leave request details to the client. Some fields are read-only and
 * automatically managed by the system, such as leaveId, numberOfDays, and status.</p>
 */
@Data
public class LeaveRequestDTO {

    /**
     * Unique identifier of the leave request.
     * <p>Read-only: generated by the system upon creation.</p>
     */
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long leaveId;

    /**
     * ID of the employee submitting the leave request.
     * <p>Cannot be null.</p>
     */
    @NotNull(message="Employee ID must not be null")
    private Long employeeId;

    /**
     * Type of leave requested.
     * <p>Cannot be null. Uses {@link LeaveTypeEnum} (Casual, Sick, Birthday).</p>
     */
    @NotNull(message="Leave type must not be null")
    private LeaveTypeEnum leaveType;

    /**
     * Start date of the leave.
     * <p>Cannot be null. Must be before or equal to endDate.</p>
     */
    @NotNull(message="Start date must not be null")
    private LocalDate startDate;

    /**
     * End date of the leave.
     * <p>Cannot be null. Must be after or equal to startDate.</p>
     */
    @NotNull(message="End date must not be null")
    private LocalDate endDate;

    /**
     * Total number of leave days for this request.
     * <p>Read-only: calculated automatically by the system.</p>
     */
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private int numberOfDays;

    /**
     * Note or reason provided by the employee for the leave.
     * <p>This field is mandatory and cannot be null or empty.</p>
     */
    @NotNull(message ="Leave note must not be null")
    private String leaveNote;

    /**
     * Current status of the leave request.
     * <p>Read-only: managed by the system. Uses {@link LeaveStatus} (Pending, Approved, Rejected).</p>
     */
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private LeaveStatus status;
}
